### ISSUE TITLE
Is there a way to find the cutset from Mongoose? 

### ISSUE THREAD

**Issue by mina1460** [ScottKolo/Mongoose#6]
I want to know which edges did Mongoose cut, is there a way to do so without needing to implement it on my own? I can see that it already computes the gain and the number of edges cut, but it doesn't specify which nodes or edges are involved in this cut. Can I extract this information or should I write my own function to do so?

If I would have to write the function myself, can you suggest an algorithm to do so? I could think of one using c++ sets to extract the cutset in O(N*log N), can anyone think of an algorithm that would run  asymptotically faster than this?

**Comment by ScottKolo** [comment]
In short, there’s not an easy way to do this because we don’t explicitly keep track of it.

Naively, you can iterate through the vertices and then each outgoing edge to determine if it’s neighbors are in the same part. That will be O(|V|*|E|), not great.

If you dig into the code a bit more, you’ll find the field ‘externalDegree’ which can be used to at least filter out vertices that are not on the boundary of the cut. While the worst case complexity is the same as the naive approach, in practice there are far fewer boundary vertices (with ‘externalDegree’ > 0). That will be closer to O(|V|).

**Comment by DrTimothyAldenDavis** [comment]
Wouldn't it just be O(E) time?  Just iterate through all the edges, (i,j).
We produce a list of nodes in each partition, so if Part(i) is not equal to
Part(j),
then the edge (i,j) is cut.

**Comment by ScottKolo** [comment]
> Wouldn't it just be O(E) time? Just iterate through all the edges, (i,j). We produce a list of nodes in each partition, so if Part(i) is not equal to Part(j), then the edge (i,j) is cut.
> […](#)

Edit: Oh, I see what you’re saying - yes, the first approach would just be O(E). Although leveraging externalDegree would still likely be the best for most graphs as |V| << |E|.

**Comment by mina1460** [comment]
Thank you for your reply. I will implement your suggestions and send it to you in case you considered adding it as a feature to Mongoose.
